spring:
  config:
    import: "classpath:.env[.properties]"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE}"
  application.name: "is-service"

token:
  secret_key: "${TOKEN_SECRET_KEY}"
  expire_time: "${TOKEN_EXPIRE_TIME}"
  refresh_time: "${TOKEN_REFRESH_TIME}"
